openapi: 3.1.0
info:
  description: "CTI manages the collection of intelligence covering existing threads\
    \ and attacks, as well as previous incidents."
  title: Cyber Threat Intelligence Service
  version: 1.0.0
servers:
- url: localhost
paths:
  /alarms:
    post:
      operationId: postAlarm
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Alarm'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IOC'
          description: OK
      summary: Send an alarm for correlation identification
      tags:
      - alarms
      x-content-type: application/json
      x-accepts:
      - application/json
      x-tags:
      - tag: alarms
  /iocs:
    get:
      operationId: getIOCs
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/IOC'
                type: array
          description: OK
      summary: Get all IOCs
      tags:
      - iocs
      x-accepts:
      - application/json
      x-tags:
      - tag: iocs
    post:
      operationId: postIOC
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IOC'
      responses:
        "200":
          description: OK
      summary: Create a new IOC entry
      tags:
      - iocs
      x-content-type: application/json
      x-accepts:
      - application/json
      x-tags:
      - tag: iocs
  /iocs/{id}:
    delete:
      operationId: deleteIOC
      parameters:
      - description: Alarm ID
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          description: OK
      summary: Delete an existing IOC entry
      tags:
      - iocs
      x-accepts:
      - application/json
      x-tags:
      - tag: iocs
    get:
      operationId: getIOC
      parameters:
      - description: Alarm ID
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IOC'
          description: OK
      summary: Get an IOC entry
      tags:
      - iocs
      x-accepts:
      - application/json
      x-tags:
      - tag: iocs
    parameters:
    - description: Alarm ID
      explode: false
      in: path
      name: id
      required: true
      schema:
        format: uuid
        type: string
      style: simple
    put:
      operationId: putIOC
      parameters:
      - description: Alarm ID
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rule'
        required: true
      responses:
        "200":
          description: OK
      summary: Modify an existing IOC entry
      tags:
      - iocs
      x-content-type: application/json
      x-accepts:
      - application/json
      x-tags:
      - tag: iocs
components:
  schemas:
    Alarm:
      example:
        data:
          key: ""
        rule:
          query: |
            SELECT * FROM logs WHERE type='email-received' AND data->'email'->>'source' NOT LIKE %example.com AND timestamp >= NOW() - INTERVAL '5 minutes';
          name: external email
          interval: '*/5 * * * *'
          threshold: 1.0800828190461012
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          threat:
            severity: high
            code: phishing
            technique: t1566.001
            tactic: ta0001
          fields:
          - field: field
            type: type
          - field: field
            type: type
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        threat:
          severity: high
          code: phishing
          technique: t1566.001
          tactic: ta0001
        ioc:
          match: "Data['email']['source'] == malicious.com"
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          threat:
            severity: high
            code: phishing
            technique: t1566.001
            tactic: ta0001
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        data:
          additionalProperties: true
          type: object
        id:
          format: uuid
          type: string
        ioc:
          $ref: '#/components/schemas/IOC'
        rule:
          $ref: '#/components/schemas/Rule'
        threat:
          $ref: '#/components/schemas/Threat'
        timestamp:
          format: date-time
          type: string
    IOC:
      example:
        match: "Data['email']['source'] == malicious.com"
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        threat:
          severity: high
          code: phishing
          technique: t1566.001
          tactic: ta0001
      properties:
        id:
          format: uuid
          type: string
        match:
          example: "Data['email']['source'] == malicious.com"
          format: SpEL
          type: string
        threat:
          $ref: '#/components/schemas/Threat'
    Rule:
      example:
        query: |
          SELECT * FROM logs WHERE type='email-received' AND data->'email'->>'source' NOT LIKE %example.com AND timestamp >= NOW() - INTERVAL '5 minutes';
        name: external email
        interval: '*/5 * * * *'
        threshold: 1.0800828190461012
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        threat:
          severity: high
          code: phishing
          technique: t1566.001
          tactic: ta0001
        fields:
        - field: field
          type: type
        - field: field
          type: type
      properties:
        fields:
          items:
            $ref: '#/components/schemas/Rule_fields_inner'
          type: array
        id:
          format: uuid
          type: string
        interval:
          example: '*/5 * * * *'
          format: cron-expression
          type: string
        name:
          example: external email
          type: string
        query:
          example: |
            SELECT * FROM logs WHERE type='email-received' AND data->'email'->>'source' NOT LIKE %example.com AND timestamp >= NOW() - INTERVAL '5 minutes';
          format: sql
          type: string
        threat:
          $ref: '#/components/schemas/Threat'
        threshold:
          minimum: 1
          type: number
    Severity:
      enum:
      - high
      - medium
      - low
      - false
      type: string
    Threat:
      example:
        severity: high
        code: phishing
        technique: t1566.001
        tactic: ta0001
      properties:
        code:
          example: phishing
          type: string
        severity:
          $ref: '#/components/schemas/Severity'
        tactic:
          example: ta0001
          type: string
        technique:
          example: t1566.001
          type: string
    Rule_fields_inner:
      example:
        field: field
        type: type
      properties:
        field:
          type: string
        type:
          type: string
