openapi: 3.1.0
info:
  description: Receives logs from endpoints and responds based on automated detection
    rules.
  title: Log Collection & Monitoring Service
  version: 1.0.0
servers:
- url: localhost
paths:
  /logs:
    get:
      operationId: getLogs
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/LogEntry'
                type: array
          description: OK
      summary: Get all log entries
      tags:
      - logs
      x-accepts:
      - application/json
      x-tags:
      - tag: logs
    post:
      operationId: postLog
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogEntry'
        required: true
      responses:
        "200":
          description: OK
      summary: Create a new log entry
      tags:
      - logs
      x-content-type: application/json
      x-accepts:
      - application/json
      x-tags:
      - tag: logs
  /logs/{id}:
    get:
      operationId: getLog
      parameters:
      - description: Log entry ID
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogEntry'
          description: OK
      summary: Get a log entry
      tags:
      - logs
      x-accepts:
      - application/json
      x-tags:
      - tag: logs
    parameters:
    - description: Log entry ID
      explode: false
      in: path
      name: id
      required: true
      schema:
        format: uuid
        type: string
      style: simple
  /rules:
    get:
      operationId: getRules
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Rule'
                type: array
          description: OK
      summary: Get all rules
      tags:
      - rules
      x-accepts:
      - application/json
      x-tags:
      - tag: rules
    post:
      operationId: postRule
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rule'
        required: true
      responses:
        "200":
          description: OK
      summary: create a new rule
      tags:
      - rules
      x-content-type: application/json
      x-accepts:
      - application/json
      x-tags:
      - tag: rules
  /rules/{id}:
    delete:
      operationId: deleteRule
      parameters:
      - description: Alarm ID
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          description: OK
      summary: Delete a rule
      tags:
      - rules
      x-accepts:
      - application/json
      x-tags:
      - tag: rules
    get:
      operationId: getRule
      parameters:
      - description: Alarm ID
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rule'
          description: OK
      summary: Get a rule
      tags:
      - rules
      x-accepts:
      - application/json
      x-tags:
      - tag: rules
    parameters:
    - description: Alarm ID
      explode: false
      in: path
      name: id
      required: true
      schema:
        format: uuid
        type: string
      style: simple
    put:
      operationId: putRule
      parameters:
      - description: Alarm ID
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rule'
        required: true
      responses:
        "200":
          description: OK
      summary: Modify a rule
      tags:
      - rules
      x-content-type: application/json
      x-accepts:
      - application/json
      x-tags:
      - tag: rules
components:
  schemas:
    Alarm:
      properties:
        data:
          additionalProperties: true
          type: object
        id:
          format: uuid
          type: string
        ioc:
          $ref: '#/components/schemas/IOC'
        rule:
          $ref: '#/components/schemas/Rule'
        threat:
          $ref: '#/components/schemas/Threat'
        timestamp:
          format: date-time
          type: string
    Endpoint:
      example:
        ip: ip
        host: host
        name: client-1
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        host:
          format: hostname
          type: string
          nullable: true
        id:
          format: uuid
          type: string
        ip:
          format: ipv4
          type: string
        name:
          example: client-1
          type: string
    IOC:
      properties:
        id:
          format: uuid
          type: string
        match:
          example: "Data['email']['source'] == malicious.com"
          format: SpEL
          type: string
        threat:
          $ref: '#/components/schemas/Threat'
    LogEntry:
      example:
        endpoint:
          ip: ip
          host: host
          name: client-1
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        data:
          key: ""
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        event: email-received
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        data:
          additionalProperties: true
          type: object
        endpoint:
          $ref: '#/components/schemas/Endpoint'
        event:
          example: email-received
          type: string
        id:
          format: uuid
          type: string
        timestamp:
          format: date-time
          type: string
    Rule:
      example:
        query: |
          SELECT * FROM logs WHERE type='email-received' AND data->'email'->>'source' NOT LIKE %example.com AND timestamp >= NOW() - INTERVAL '5 minutes';
        name: external email
        interval: '*/5 * * * *'
        threshold: 1.0800828190461012
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        threat:
          severity: high
          code: phishing
          technique: t1566.001
          tactic: ta0001
        fields:
        - field: field
          type: type
        - field: field
          type: type
      properties:
        fields:
          items:
            $ref: '#/components/schemas/Rule_fields_inner'
          type: array
        id:
          format: uuid
          type: string
        interval:
          example: '*/5 * * * *'
          format: cron-expression
          type: string
        name:
          example: external email
          type: string
        query:
          example: |
            SELECT * FROM logs WHERE type='email-received' AND data->'email'->>'source' NOT LIKE %example.com AND timestamp >= NOW() - INTERVAL '5 minutes';
          format: sql
          type: string
        threat:
          $ref: '#/components/schemas/Threat'
        threshold:
          minimum: 1
          type: number
    Severity:
      enum:
      - high
      - medium
      - low
      - false
      type: string
    Threat:
      example:
        severity: high
        code: phishing
        technique: t1566.001
        tactic: ta0001
      properties:
        code:
          example: phishing
          type: string
        severity:
          $ref: '#/components/schemas/Severity'
        tactic:
          example: ta0001
          type: string
        technique:
          example: t1566.001
          type: string
    Rule_fields_inner:
      example:
        field: field
        type: type
      properties:
        field:
          type: string
        type:
          type: string
